# Generated by Django 5.0.4 on 2025-04-22 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_alimentares', to=settings.AUTH_USER_MODEL)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cafe_da_manha', 'Café da manhã'), ('lanche_manha', 'Lanche da manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da tarde'), ('jantar', 'Jantar'), ('ceia', 'Ceia')], max_length=50)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planoalimentar.diasemana')),
                ('plano_alimentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='planoalimentar.planoalimentar')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendado', models.TextField()),
                ('substituicoes', models.TextField()),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='planoalimentar.refeicao')),
            ],
        ),
    ]
